"""Agregar tabla escena_personaje para Party

Revision ID: b48f48c83275
Revises: b2d8ec20a4cc
Create Date: 2026-09-24 13:13:56.552149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48f48c83275'
down_revision: Union[str, Sequence[str], None] = 'b2d8ec20a4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escenas', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_escenas_padre_id', 'escenas', ['escena_padre_id'], ['id'])
        batch_op.create_foreign_key('fk_escenas_mensaje_id', 'mensajes', ['mensaje_bifurcacion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escenas', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_escenas_padre_id', type_='foreignkey')
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_escenas_mensaje_id', type_='foreignkey')

    # ### end Alembic commands ###
